let messages = [
    {'id': 70, 'categoria':'Madres', 'mensaje':'Madre, en este día especial quiero expresarte mi gratitud por ser la persona más importante en mi vida. Gracias por todo lo que has hecho por mí, por tus sacrificios, tu amor incondicional y por ser mi ejemplo a seguir. Tus palabras de aliento y tus abrazos reconfortantes me han dado fuerza en los momentos difíciles. Eres la mejor madre del mundo y te quiero con todo mi corazón. Feliz día de la madre.'},
    {'id': 71, 'categoria':'Madres', 'mensaje':'Hoy es el día en que se celebra a las madres, pero para mí, cada día es un día para agradecerte por ser mi guía, mi amiga y mi confidente. Gracias por ser mi compañera de vida y por estar presente en los momentos más importantes. Eres una persona única e irreemplazable en mi vida, y aunque a veces no lo demuestre, te quiero mucho. Feliz día de la madre.'},
    {'id': 72, 'categoria':'Madres', 'mensaje':'Querida madre, hoy quiero dedicarte unas palabras para recordarte lo importante que eres para mí. Gracias por tu amor incondicional, tu paciencia y tu apoyo constante. Eres mi héroe y siempre has sido mi roca en los momentos difíciles. Gracias por haberme dado la vida, por haberme enseñado a caminar y por guiarme en mi camino. Espero poder ser una fuente de orgullo para ti. Feliz día de la madre.'},
    {'id': 1, 'categoria':'Cumpleaños', 'mensaje':'¡Feliz cumpleaños! Que en este día tan especial, Dios te bendiga con mucha felicidad. Que en la vida siempre encuentres razones para sonreír y dar gracias.'},
    {'id': 2, 'categoria':'Familia', 'mensaje':'Desde que naciste eres dueña de una parte de mi corazón, te amo y admiro por la mujer valiosa y soñadora en la que te has convertido… el mundo se ve tan pequeño para ti mi hermana del alma.'},
    {'id': 3, 'categoria':'Familia', 'mensaje':'Pienso que se quedaron cortos al hablarme de tus dones y virtudes,  eres maravillosa y queremos darte las gracias por tus atenciones y ser la mejor anfitriona, te esperamos en casa.'},
    {'id': 4, 'categoria':'Cumpleaños', 'mensaje':'Deseo que el amor y la alegría estén de tu lado en todos los instantes de tu vida. Eres una persona muy especial y considero que soy bendecida por contar con tu amistad y con tu cariño.'},
    {'id': 5, 'categoria':'Cumpleaños', 'mensaje':'Lo mejor para ti en este día, que sigas cumpliendo muchos años más y llenando de alegría los corazones de todos.'},
    {'id': 6, 'categoria':'Amor', 'mensaje':'Es fácil amar a alguien cuando todo es perfecto, mantener ese amor, durante los momentos dificiles, es lo que lo hace  incondicional. Te amo'},
    {'id': 7, 'categoria':'Cumpleaños', 'mensaje':'¡Feliz cumpleaños! Que el Señor sea tu fuerza y vigor todos los días que te dé en esta tierra. Gracias por ser tan especial ♥'},
    {'id': 8, 'categoria':'Amor', 'mensaje':'Te miro, sonrió y siempre me preguntó... ¿Qué es eso que haces para gustarme tanto?'},
    {'id': 9, 'categoria':'Cumpleaños', 'mensaje':'Mis mejores deseos para tí, que el Señor te bendiga con mucha salud y prosperidad para ti y tu familia. Continua siendo esa mujer luchadora, amorosa, sencilla y amable.'},    
    {'id': 10, 'categoria':'Madres', 'mensaje':'¡Feliz Día de la Madre! Gracias por ser mi roca y mi apoyo en todo momento.'},   
    {'id': 11, 'categoria':'Madres', 'mensaje':'Madre, tu amor incondicional y sacrificio no tienen límites. ¡Te quiero mucho!'},   
    {'id': 12, 'categoria':'Madres', 'mensaje':'Hoy es un día especial para honrar a todas las madres del mundo. ¡Gracias por todo lo que haces!'},   
    {'id': 13, 'categoria':'Madres', 'mensaje':'Las palabras no pueden expresar todo lo que significas para mí, mamá. ¡Feliz Día de la Madre!'},   
    {'id': 14, 'categoria':'Madres', 'mensaje':'Mamá, gracias por enseñarme a ser fuerte, valiente y amable. ¡Eres mi heroína!'},   
    {'id': 15, 'categoria':'Madres', 'mensaje':'Hoy celebro el amor inquebrantable y la dedicación que siempre has mostrado hacia tu familia. ¡Feliz Día de la Madre!'},   
    {'id': 16, 'categoria':'Madres', 'mensaje':'No hay nada más importante que el amor de una madre. ¡Gracias por ser mi ejemplo a seguir!'},   
    {'id': 17, 'categoria':'Madres', 'mensaje':'En este día de las madres, recuerda que eres una mujer valiente y admirable que siempre está ahí para su familia.'},   
    {'id': 18, 'categoria':'Madres', 'mensaje':'Mamá, gracias por siempre apoyarme, escucharme y amarme incondicionalmente. ¡Feliz Día de la Madre!'},   
    {'id': 19, 'categoria':'Madres', 'mensaje':'Hoy es el día perfecto para demostrarte lo agradecido que estoy por todo lo que haces por mí. ¡Te quiero mucho, mamá!'},   
    {'id': 20, 'categoria':'Amistad', 'mensaje':'La amistad es uno de los regalos más hermosos de la vida. ¡Gracias por ser mi amiga!'},
    {'id': 21, 'categoria':'Amistad', 'mensaje':'La amistad es como una flor que necesita cuidado y atención para florecer. ¡Gracias por cuidar nuestra amistad!'},
    {'id': 22, 'categoria':'Amistad', 'mensaje':'Los amigos son la familia que elegimos. ¡Gracias por ser parte de mi familia!'},
    {'id': 23, 'categoria':'Amistad', 'mensaje':'Una verdadera amistad es aquella que dura a través de los altibajos de la vida. ¡Gracias por ser mi amigo de verdad!'},
    {'id': 24, 'categoria':'Amistad', 'mensaje':'Los amigos son la luz en los días oscuros. ¡Gracias por ser mi luz!'},
    {'id': 25, 'categoria':'Amistad', 'mensaje':'La amistad es un tesoro que debemos cuidar y valorar. ¡Gracias por ser mi tesoro!'},
    {'id': 26, 'categoria':'Amistad', 'mensaje':'La amistad no se trata de estar juntos todo el tiempo, sino de saber que siempre puedes contar con alguien. ¡Gracias por estar siempre ahí para mí!'},
    {'id': 27, 'categoria':'Amistad', 'mensaje':'Los amigos son como las estrellas, siempre están ahí aunque no los veamos. ¡Gracias por ser mi estrella!'},
    {'id': 28, 'categoria':'Amistad', 'mensaje':'La amistad es una conexión del corazón que trasciende el tiempo y la distancia. ¡Gracias por mantener esa conexión conmigo!'},
    {'id': 29, 'categoria':'Amistad', 'mensaje':'Los amigos son la sal de la vida, sin ellos todo sería insípido. ¡Gracias por dar sabor a mi vida!'},
    {'id': 30, 'categoria':'Cumpleaños', 'mensaje':'¡Feliz cumpleaños! Espero que tu día esté lleno de amor, alegría y muchas bendiciones.'}, 
    {'id': 31, 'categoria':'Cumpleaños', 'mensaje':'En tu cumpleaños te deseo un año lleno de nuevas oportunidades, crecimiento y éxito. ¡Feliz cumpleaños!'}, 
    {'id': 32, 'categoria':'Cumpleaños', 'mensaje':'Espero que tu cumpleaños sea tan especial como tú eres para mí. ¡Feliz cumpleaños, amigo/a!'}, 
    {'id': 33, 'categoria':'Cumpleaños', 'mensaje':'Que este nuevo año de vida te traiga todo lo que deseas y más. ¡Feliz cumpleaños!'}, 
    {'id': 34, 'categoria':'Cumpleaños', 'mensaje':'Hoy celebramos el día en que el mundo se hizo un poco más brillante gracias a tu llegada. ¡Feliz cumpleaños!'}, 
    {'id': 35, 'categoria':'Cumpleaños', 'mensaje':'Que en tu cumpleaños recibas todo el amor, la felicidad y las sonrisas que mereces. ¡Feliz cumpleaños!'}, 
    {'id': 36, 'categoria':'Cumpleaños', 'mensaje':'Espero que este nuevo año de vida esté lleno de aventuras emocionantes, momentos inolvidables y mucha felicidad. ¡Feliz cumpleaños!'}, 
    {'id': 37, 'categoria':'Cumpleaños', 'mensaje':'Hoy celebramos la vida de alguien muy especial. ¡Feliz cumpleaños y que sigas siendo tan maravilloso/a como siempre!'}, 
    {'id': 38, 'categoria':'Cumpleaños', 'mensaje':'En tu cumpleaños quiero agradecerte por ser un/a amigo/a tan increíble y por llenar mi vida de risas y buenos momentos. ¡Feliz cumpleaños!'}, 
    {'id': 39, 'categoria':'Cumpleaños', 'mensaje':'Espero que tu cumpleaños sea tan dulce como el pastel que lo celebra. ¡Feliz cumpleaños y que sigas endulzando la vida de todos los que te rodean!'}, 
    {'id': 40, 'categoria':'Amor', 'mensaje':'Eres mi sol en los días oscuros y mi compañero/a en las alegrías de la vida. Te amo.'},  
    {'id': 41, 'categoria':'Amor', 'mensaje':'Amarte es fácil porque eres lo mejor que me ha pasado. Gracias por ser mi compañero/a de vida.'},  
    {'id': 42, 'categoria':'Amor', 'mensaje':'Contigo al lado, cada momento es especial y cada día es una aventura. Te amo más cada día.'},  
    {'id': 43, 'categoria':'Amor', 'mensaje':'Eres mi amor verdadero, mi mejor amigo/a y mi alma gemela. Gracias por estar siempre a mi lado.'},  
    {'id': 44, 'categoria':'Amor', 'mensaje':'En tus brazos encuentro mi hogar y en tu corazón mi paz. Te amo con todo mi ser.'},  
    {'id': 45, 'categoria':'Amor', 'mensaje':'Tú eres mi felicidad, mi motivación y mi todo. Gracias por ser mi compañero/a de vida.'},  
    {'id': 46, 'categoria':'Amor', 'mensaje':'Cada momento contigo es una bendición y un regalo del universo. Te amo por siempre.'},  
    {'id': 47, 'categoria':'Amor', 'mensaje':'Contigo he encontrado un amor que nunca creí posible. Gracias por ser mi pareja, mi amor y mi amigo/a.'},  
    {'id': 48, 'categoria':'Amor', 'mensaje':'En tus ojos encuentro la chispa de la vida y en tus labios el sabor del amor verdadero. Te amo cada día más.'},  
    {'id': 49, 'categoria':'Amor', 'mensaje':'Eres mi complemento perfecto, mi media naranja y mi amor para siempre. Te amo con todo mi corazón.'},  
    {'id': 50, 'categoria':'Aniversario', 'mensaje':'Feliz aniversario de nuestro amor. Gracias por hacer que cada día sea especial.'},
    {'id': 51, 'categoria':'Aniversario', 'mensaje':'En este aniversario quiero decirte que te amo hoy, mañana y siempre. Feliz aniversario mi amor.'},
    {'id': 52, 'categoria':'Aniversario', 'mensaje':'Celebrando otro año juntos, lleno de amor, felicidad y aventuras emocionantes. Feliz aniversario.'},
    {'id': 53, 'categoria':'Aniversario', 'mensaje':'Gracias por hacer que cada día valga la pena. Feliz aniversario mi amor.'},
    {'id': 54, 'categoria':'Aniversario', 'mensaje':'Han sido los mejores años de mi vida gracias a ti. Feliz aniversario mi amor.'},
    {'id': 55, 'categoria':'Aniversario', 'mensaje':'Celebrando otro año de amor, risas y mucha felicidad. Feliz aniversario a mi compañero/a de vida.'},
    {'id': 56, 'categoria':'Aniversario', 'mensaje':'Que este aniversario sea el inicio de un nuevo año lleno de aventuras y momentos inolvidables. Feliz aniversario mi amor.'},
    {'id': 57, 'categoria':'Aniversario', 'mensaje':'Han sido años increíbles a tu lado, y no puedo esperar a lo que venga. Feliz aniversario de nuestro amor.'},
    {'id': 58, 'categoria':'Aniversario', 'mensaje':'Contigo he encontrado el amor verdadero, la amistad y la compañía perfecta. Feliz aniversario mi amor.'},
    {'id': 59, 'categoria':'Aniversario', 'mensaje':'Gracias por ser mi pareja, mi compañero/a de vida y mi mejor amigo/a. Feliz aniversario de nuestro amor.'},
    {'id': 60, 'categoria':'Familia', 'mensaje':'Eres mi familia y siempre estaré aquí para apoyarte en todo lo que necesites. Te quiero mucho.'}, 
    {'id': 61, 'categoria':'Familia', 'mensaje':'Eres una de las personas más importantes en mi vida y siempre te llevaré en mi corazón. Te amo, familia.'}, 
    {'id': 62, 'categoria':'Familia', 'mensaje':'Agradezco a la vida por tener a alguien como tú en mi familia. Gracias por ser mi apoyo y mi inspiración.'}, 
    {'id': 63, 'categoria':'Familia', 'mensaje':'Eres mi familia y siempre estarás en mis pensamientos y en mi corazón. Te quiero mucho.'}, 
    {'id': 64, 'categoria':'Familia', 'mensaje':'Gracias por ser un pilar en mi vida y por ayudarme a crecer como persona. Te quiero mucho, familia.'}, 
    {'id': 65, 'categoria':'Familia', 'mensaje':'Eres mi familia y siempre estaré aquí para celebrar tus éxitos y apoyarte en los momentos difíciles. Te amo.'}, 
    {'id': 66, 'categoria':'Familia', 'mensaje':'Eres una bendición en mi vida y agradezco a la vida por tenerte en mi familia. Te quiero mucho.'}, 
    {'id': 67, 'categoria':'Familia', 'mensaje':'Gracias por ser una parte importante en mi vida y por hacer que cada momento juntos sea especial. Te amo, familia.'}, 
    {'id': 68, 'categoria':'Familia', 'mensaje':'Eres mi familia y siempre estarás en mis oraciones y en mis pensamientos. Te quiero mucho.'}, 
    {'id': 69, 'categoria':'Familia', 'mensaje':'Aunque a veces discutamos y tengamos diferencias, siempre te tendré en mi corazón porque eres mi familia. Te amo.'},     
]

// {'id': 10, 'categoria':'', 'mensaje':''},    